### ISSUE TITLE
Webpack building as a third degree dependency fails

### ISSUE THREAD

**Issue by TekSiDoT** [rootslab/qap#2]
I'm using qap as a dependency of dns-js as a dependency of mdns-js. When building with webpack, the following error occurs:

```
ERROR in ./~/qap/lib/qap.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../package in D:\...\node_modules\qap\lib @ ./~/qap/lib/qap.js 12:18-41
```
I was able to resolve this issue by changing the export in [qap.js](https://github.com/rootslab/qap/blob/master/lib/qap.js#L12) from 
`exports.version = require('../package').version;`
to 
`exports.version = require('../').version;`

Would this be an option for the general distributed package or is this a local requirement I'll have to create a fork for?

**Comment by TekSiDoT** [comment]
@rootslab  I'll take that as an no ... ?

**Comment by rootslab** [comment]
Yes, sorry, I can't help you for now, I don't use webpack.
I think that the matter is: how webpack resolve modules (in your OS)?
What is the output of __dirname property?

**Comment by rootslab** [comment]
@TekSiDoT I'll probably remove version from all my modules in next releases.

**Comment by TekSiDoT** [comment]
Great to hear, thank you for your work!

**Comment by rootslab** [comment]
@TekSiDoT, version was removed
